// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtYoq_-SySpdtxN9RzEKL38AMan34P640',
    appId: '1:979122525797:web:f8d68318a5a680724d988c',
    messagingSenderId: '979122525797',
    projectId: 'voxai-quest',
    authDomain: 'voxai-quest.firebaseapp.com',
    storageBucket: 'voxai-quest.firebasestorage.app',
    measurementId: 'G-LKRP70XDJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC67mjKunDsrot3Uh6Tg9XjNn1hhFv_5Co',
    appId: '1:979122525797:android:a44a492d7a6fec854d988c',
    messagingSenderId: '979122525797',
    projectId: 'voxai-quest',
    storageBucket: 'voxai-quest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwT54xT0vwRAPJyHzkOFef7L-dhSk3lxQ',
    appId: '1:979122525797:ios:d36e0e4d5e23889f4d988c',
    messagingSenderId: '979122525797',
    projectId: 'voxai-quest',
    storageBucket: 'voxai-quest.firebasestorage.app',
    androidClientId: '979122525797-mtsk50uopobsq7lpm0pq2bajceea878e.apps.googleusercontent.com',
    iosClientId: '979122525797-c6id3b5rvl068de8e70rh6ovo5sp84vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.voxaiQuest',
  );

}
